name: Python CI TEST

on:
  push:
    branches: [ main ]  # Se ejecutará en cada push a la rama principal
  pull_request:
    branches: [ main ]  # También en cada pull request a main

jobs:
  build:
    runs-on: ubuntu-latest  # Se ejecuta en un entorno Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Clona el código en la máquina virtual

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Versión de Python a utilizar

    - name: Install dependencies
      run: pip install pytest  # Instala pytest para correr las pruebas

    - name: Run tests
      run: python -m unittest discover  # Ejecuta todas las pruebas unitarias
